export const SYSTEM_MODULES = [
  {
    group: null,
    key: 'dashboard',
    title: 'Dashboard',
    icon: 'dashboard',
    route: '/app',
    showInMenu: true,
    order: 1,
    permissions: [
      { label: 'Exibir Menu', value: 'dashboard.menu' },
      { label: 'Visualizar', value: 'dashboard.view' },
    ],
  },

  {
    group: 'COMPRAS',
    key: 'requests',
    title: 'Solicitações',
    icon: 'description',
    route: '/app/buy/requests',
    showInMenu: true,
    order: 10,
    permissions: [
      { label: 'Exibir Menu', value: 'requests.menu' },
      { label: 'Visualizar', value: 'requests.view' },
      { label: 'Criar', value: 'requests.create' },
      { label: 'Editar', value: 'requests.edit' },
      { label: 'Excluir', value: 'requests.delete' },
    ],
  },

  {
    group: 'COMPRAS',
    key: 'budget',
    title: 'Orçamentos',
    icon: 'request_quote',
    route: '/app/buy/budget',
    showInMenu: true,
    order: 11,
    permissions: [
      { label: 'Exibir Menu', value: 'budget.menu' },
      { label: 'Visualizar', value: 'budget.view' },
      { label: 'Editar', value: 'budget.edit' },
      { label: 'Finalizar', value: 'budget.finish' },
    ],
  },

  {
    group: 'COMPRAS',
    key: 'revision',
    title: 'Revisão',
    icon: 'grading',
    route: '/app/buy/revision',
    showInMenu: true,
    order: 12,
    permissions: [
      { label: 'Exibir Menu', value: 'revision.menu' },
      { label: 'Visualizar', value: 'revision.view' },
      { label: 'Editar', value: 'revision.edit' },
      { label: 'Enviar p/ Análise', value: 'revision.send_analysis' },
    ],
  },

  {
    group: 'COMPRAS',
    key: 'analysis',
    title: 'Análise',
    icon: 'analytics',
    route: '/app/buy/analysis',
    showInMenu: true,
    order: 13,
    permissions: [
      { label: 'Exibir Menu', value: 'analysis.menu' },
      { label: 'Visualizar', value: 'analysis.view' },
      { label: 'Deferir', value: 'analysis.defer' },
      { label: 'Indeferir', value: 'analysis.indefer' },
      { label: 'Em Espera', value: 'analysis.wait' },
      { label: 'Enviar p/ Orçamento', value: 'analysis.send_budget' },
    ],
  },

  {
    group: 'COMPRAS',
    key: 'payment',
    title: 'Pagamentos',
    icon: 'payment',
    route: '/app/buy/payment',
    showInMenu: true,
    order: 14,
    permissions: [
      { label: 'Exibir Menu', value: 'payment.menu' },
      { label: 'Visualizar', value: 'payment.view' },
      { label: 'Finalizar Compra', value: 'payment.finish' },
    ],
  },

  {
    group: 'COMPRAS',
    key: 'tracking',
    title: 'Rastreio',
    icon: 'visibility',
    route: '/app/buy/tracking',
    showInMenu: true,
    order: 15,
    permissions: [
      { label: 'Exibir Menu', value: 'tracking.menu' },
      { label: 'Visualizar', value: 'tracking.view' },
      { label: 'Confirmar Entrega', value: 'tracking.deliver' },
      { label: 'Finalizar Processo', value: 'tracking.finish' },
    ],
  },

  {
    group: 'COMPRAS',
    key: 'history',
    title: 'Histórico',
    icon: 'history',
    route: '/app/buy/history',
    showInMenu: true,
    order: 16,
    permissions: [
      { label: 'Exibir Menu', value: 'history.menu' },
      { label: 'Visualizar', value: 'history.view' },
      { label: 'Solicitar Reanálise', value: 'history.reanalyze' },
      { label: 'Solicitar Reforço', value: 'history.reinforcement' },
      { label: 'Copiar Solicitação', value: 'history.copy' },
    ],
  },

  {
    group: 'COMPRAS',
    key: 'preferences',
    title: 'Preferências',
    icon: 'settings',
    route: '/app/buy/preferences',
    showInMenu: true,
    order: 17,
    permissions: [
      { label: 'Exibir Menu', value: 'preferences.menu' },
      { label: 'Visualizar', value: 'preferences.view' },
      { label: 'Criar Categoria', value: 'preferences.create' },
      { label: 'Editar', value: 'preferences.edit' },
      { label: 'Excluir Categoria', value: 'preferences.delete' },
    ],
  },

  {
    group: 'CONFIGURAÇÕES',
    key: 'users',
    title: 'Usuários',
    icon: 'people',
    route: '/app/settings/users',
    showInMenu: true,
    order: 90,
    permissions: [
      { label: 'Exibir Menu', value: 'users.menu' },
      { label: 'Visualizar', value: 'users.view' },
      { label: 'Criar', value: 'users.create' },
      { label: 'Editar', value: 'users.edit' },
      { label: 'Excluir', value: 'users.delete' },
    ],
  },

  {
    group: 'CONFIGURAÇÕES',
    key: 'departments',
    title: 'Setores',
    icon: 'business',
    route: '/app/settings/departments',
    showInMenu: true,
    order: 91,
    permissions: [
      { label: 'Exibir Menu', value: 'departments.menu' },
      { label: 'Visualizar', value: 'departments.view' },
      { label: 'Criar', value: 'departments.create' },
      { label: 'Editar', value: 'departments.edit' },
      { label: 'Excluir', value: 'departments.delete' },
    ],
  },

  {
    group: 'CONFIGURAÇÕES',
    key: 'roles',
    title: 'Perfil de Usuário',
    icon: 'admin_panel_settings',
    route: '/app/settings/roles',
    showInMenu: true,
    order: 92,
    permissions: [
      { label: 'Exibir Menu', value: 'roles.menu' },
      { label: 'Visualizar', value: 'roles.view' },
      { label: 'Criar', value: 'roles.create' },
      { label: 'Editar', value: 'roles.edit' },
      { label: 'Excluir', value: 'roles.delete' },
    ],
  },

  {
    group: 'CONFIGURAÇÕES',
    key: 'logs',
    title: 'Logs',
    icon: 'history',
    route: '/app/settings/logs',
    showInMenu: true,
    order: 99,
    permissions: [
      { label: 'Exibir Menu', value: 'logs.menu' },
      { label: 'Visualizar', value: 'logs.view' },
    ],
  },
]
